Build change log point generator to capture affected paths, culprits and commit messages
jenkinsci/influxdb-plugin pull request #14
Opened 2017-04-17 14:03 UTC by adityacs

Captures below metrics:

Affected paths -- Files changed in the commit
  Data type: comma separated string

Culprits -- Authors
  Data type: comma separated string

Messages -- Commit messages
  Data type: comma separated string

Commit Count -- Total number of commits for the particular build
   Data type: int

2017-04-17 14:11 UTC, adityacs commented
@asimell I am not sure if it is good practice to store string values which are very long in length in InfluxDB. However, this feature helps to capture metrics on change log. It's good if this is merged.

2017-05-02 12:23 UTC, asimell commented on src/main/java/jenkinsci/plugins/influxdb/generators/ChangeLogPointGenerator.java
> +				.field("commit_messages", this.getMessages())
Due to influx-java version update, these function calls are now deprecated. You should use .addField() instead of .field().

2017-05-02 12:27 UTC, asimell requested changes
Due to influx-java version update, `.field()` function calls are now deprecated. You should use `.addField()` instead of `.field()`.

2017-05-03 05:58 UTC, adityacs commented
@asimell I have made the changes.

2017-05-03 06:04 UTC, asimell approved these changes

2017-05-03 07:10 UTC, asimell commented
@adityacs The build sends now sends changelog data even if there are no changes or even if the build is not using SCM at all. I doubt this is desired behaviour?

2017-05-03 08:45 UTC, adityacs commented
@asimell It sends empty data if there are no changes. If there is no SCM it won't send because the build instance will not be of type abstractbuild without scm. 
I will change this. I will add a check to read the data and publish only if there is change.

2017-05-03 09:55 UTC, adityacs commented
@asimell I have added the check. 
[https://github.com/adityacs/influxdb-plugin/blob/master/src/main/java/jenkinsci/plugins/influxdb/generators/ChangeLogPointGenerator.java#L38](url)

2017-05-03 12:10 UTC, merged